insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Janine', 'McAuslene', 'Brigstock', '1970-02-19 19:06:04', '48 Oak Valley Park', 'l89aB84q1Q', 'M76kriHxiR6', 11, 12);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Cart', 'Wright', 'Sidey', '1989-04-23 17:17:32', '58530 Center Alley', 'tYLmJ2Eygl', 'hauxHf', 7, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Reggie', 'Squirrell', 'Garz', '1985-05-23 22:09:49', '0 Troy Court', 'CqYw24d', 'IKkIdM7yZnT', 9, 12);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Dido', 'McKoy', 'Hiscoke', '1978-10-23 12:11:08', '92129 Farwell Parkway', 'EvIqnj9', 'YckG9FmX8', 12, 12);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Alene', 'Risom', 'Dauby', '1997-12-18 07:10:52', '5598 Heffernan Street', 'BbUsmCyA', '9ttRvE', 8, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Kyle', 'McLaughlan', 'Gifford', '1974-03-15 18:17:12', '4602 Garrison Parkway', 'ns87sW', 'Bv6mKI', 12, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Roberta', 'Plaunch', 'Hise', '1994-01-21 07:10:08', '810 Toban Crossing', 'yeYwX4', 'bpUzx5tRcGIH', 9, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Cherilynn', 'Hubbert', 'Hawkswell', '1974-02-22 03:05:51', '0718 Kennedy Parkway', '8Bu7LmFdrTZ', 'gdSDWhfGjmD', 12, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Crawford', 'Hadley', 'Sessuns', '1982-06-18 13:21:10', '5004 Cherokee Crossing', 'Iq5adZ', 'YcFsT4mLBzBL', 8, 12);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Carroll', 'Allner', 'Westoll', '1999-10-12 23:57:34', '80 American Park', 'yovmdfp', 'zOw3U4SOLbK', 10, 11);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Matilda', 'Dawtre', 'Purves', '1970-04-28 00:36:44', '620 Lyons Point', 'yZccVZ1I', 'aZvvzgeA', 12, 11);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Dill', 'Hallaways', 'Casper', '1988-03-16 15:36:16', '78 Boyd Place', 'TtXFzLT5Iz', 'BPeLaGOy', 12, 11);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Ealasaid', 'MacFadden', 'Vorley', '1987-01-15 22:20:35', '1 Sherman Court', 'Uj2154', 'fvJAYuP', 11, 10);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Jodie', 'Roles', 'Sagg', '1977-06-14 03:55:16', '580 Westerfield Center', 'iJbbreko5', 'aefHDUQR', 11, 11);
insert into persona (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, horario_entrada_empleado, horario_salida_empleado) values ('Luce', 'Kaesmakers', 'Clout', '1990-04-12 01:33:30', '230 Eagle Crest Point', 'dw0HI3v', 'tBWvW9l', 11, 11);


SELECT * FROM persona WHERE horario_entrada_empleado IS NOT NULL AND horario_salida_empleado IS NOT NULL;