insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (101, 'Shandy', 'Powelee', 'Bridgeman', '2008-01-04', '6516 Columbus Park', 'T3r4mnIGDvK1', 'sbridgeman0', 145200);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (102, 'Francisco', 'Caustick', 'Di Carlo', '2019-09-14', '8 Gale Parkway', 'eaM9SDmpK', 'fdicarlo1', 109641);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (103, 'Monro', 'Urien', 'Baumann', '1991-04-29', '6973 Vermont Court', '2iXl3FNYQb93', 'mbaumann2', 106164);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (104, 'Trent', 'MacCrossan', 'Perkis', '2009-11-29', '99 Troy Terrace', 'aHkIY09', 'tperkis3', 100532);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (105, 'Arther', 'Burgiss', 'Mardling', '1981-08-30', '03 Saint Paul Drive', '0ew7Ym9', 'amardling4', 181150);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (106, 'Janka', 'Whardley', 'Moulson', '1981-02-06', '5992 Gulseth Alley', '851rBa', 'jmoulson5', 187866);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (107, 'Cassandre', 'Melson', 'Theobalds', '1981-03-31', '14 Nova Trail', '9OnhjCgGz', 'ctheobalds6', 161310);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (108, 'Haley', 'Marshallsay', 'Barwood', '2016-04-10', '8240 Linden Parkway', 'qpBPswppXTp', 'hbarwood7', 185462);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (109, 'Paige', 'Santacrole', 'Alven', '2018-03-15', '82 Marquette Crossing', 'W0xnCbbdJ', 'palven8', 138802);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (110, 'Niko', 'Joselevitz', 'Alforde', '1985-06-19', '279 Memorial Crossing', 'VJbuR6dRJREj', 'nalforde9', 172445);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (111, 'Shell', 'Dye', 'Darkin', '2008-04-11', '874 American Ash Trail', 'ZkEplxq', 'sdarkina', 158734);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (112, 'Madlen', 'Burgyn', 'Allchin', '2003-05-08', '2818 Fuller Parkway', 'MJet5A', 'mallchinb', 129619);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (113, 'Jacqui', 'Degue', 'Gambrell', '1987-06-13', '324 Continental Street', '5kSTgfy7Ze9', 'jgambrellc', 148333);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (114, 'Rollins', 'Marrill', 'Cato', '2003-05-25', '9935 Gina Lane', '3rDeHU2z9DQ', 'rcatod', 136134);
insert into persona (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, domicilio, clave, nombre_usuario, numero_empleado) values (115, 'Emmit', 'Overland', 'Solley', '1986-11-01', '73 Bay Trail', '8QSVxO8mDUW', 'esolleye', 128276);

SELECT * FROM persona WHERE numero_empleado IS NOT NULL;